[project]
name = 'clarinet-backend'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 2
epoch = 2.4

[contracts.my-nft]
path = 'contracts/my-nft.clar'
clarity_version = 2
epoch = 2.4

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
